# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 05:59:57 2018 from module list in Acme::CPANLists::Import::Caching version 0.03.

package Acme::CPANModules::Import::Caching;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://cpan.robm.fastmail.fm/cache_perf.html] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Cache::FastMmap" },
                   { module => "Cache::FileCache" },
                   { module => "Cache::Mmap" },
                   { module => "Cache::SharedMemoryCache" },
                   { module => "Cache::SizeAwareFileCache" },
                   { module => "IPC::MM" },
                   { module => "IPC::ShareLite" },
                   { module => "MLDBM::Sync::SDBM_File" },
                 ],
  summary     => "Comparison of different Perl caching modules (2002-2005)",
};

# ABSTRACT: Comparison of different Perl caching modules (2002-2005)

