# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:02:08 2018 from module list in Acme::CPANLists::Import::CombinationsAndPermutations version 0.03.

package Acme::CPANModules::Import::CombinationsAndPermutations;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/dana_jacobsen/2015/02/short-survey-of-modules-for-combinations-and-permutations.html] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Algorithm::Combinatorics" },
                   { module => "Algorithm::FastPermute" },
                   { module => "Algorithm::Loops" },
                   { module => "Algorithm::Permute" },
                   { module => "Iterator::Misc" },
                   { module => "List::Permutor" },
                   { module => "Math::Combinatorics" },
                   { module => "Math::Counting" },
                   { module => "Math::Disarrange::List" },
                   { module => "Math::GSL::Combination" },
                   { module => "Math::GSL::Permutation" },
                   { module => "Math::Pari" },
                   { module => "Math::Permute::Array" },
                   { module => "Math::Permute::List" },
                   { module => "ntheory" },
                 ],
  summary     => "Short survey of modules for combinations and permutations (2015)",
};

# ABSTRACT: Short survey of modules for combinations and permutations (2015)

