# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:05:02 2018 from module list in Acme::CPANLists::Import::DatesPart1 version 0.03.

package Acme::CPANModules::Import::DatesPart1;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/buddy_burden/2015/09/a-date-with-cpan-part-1-state-of-the-union.html] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Class::Date" },
                   { module => "DBIx::Class" },
                   { module => "DBIx::Class::InflateColumn::DateTimeX::Immutable" },
                   { module => "Date::Calc" },
                   { module => "Date::Format" },
                   { module => "Date::Handler" },
                   { module => "Date::Manip" },
                   { module => "Date::Manip::Date" },
                   { module => "Date::Parse" },
                   { module => "Date::Piece" },
                   { module => "Date::Simple" },
                   { module => "DateTime" },
                   { module => "DateTime::Format::DateManip" },
                   { module => "DateTime::Moonpig" },
                   { module => "DateTimeX::Immutable" },
                   { module => "Panda::Date" },
                   { module => "Time::Local" },
                   { module => "Time::Moment" },
                   { module => "Time::Object" },
                   { module => "Time::ParseDate" },
                   { module => "Time::Piece" },
                 ],
  summary     => "CPAN modules for processing dates - Part 1 (2015)",
};

1;
# ABSTRACT: CPAN modules for processing dates - Part 1 (2015)

