# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:02:08 2018 from module list in Acme::CPANLists::Import::DatesPart2 version 0.03.

package Acme::CPANModules::Import::DatesPart2;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/buddy_burden/2015/10/a-date-with-cpan-part-2-target-first-aim-afterwards.html] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Date::Parse" },
                   { module => "Date::Piece" },
                   { module => "Time::Moment" },
                   { module => "Time::ParseDate" },
                   { module => "Time::Piece" },
                 ],
  summary     => "CPAN modules for processing dates - Part 2",
};

# ABSTRACT: CPAN modules for processing dates - Part 2

