# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:05:03 2018 from module list in Acme::CPANLists::Import::JSONDecoders version 0.03.

package Acme::CPANModules::Import::JSONDecoders;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://perlmaven.com/comparing-the-speed-of-json-decoders] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Benchmark" },
                   { module => "Cpanel::JSON::XS" },
                   { module => "JSON" },
                   { module => "JSON::MaybeXS" },
                   { module => "JSON::PP" },
                   { module => "JSON::XS" },
                   { module => "Text::CSV" },
                   { module => "Text::CSV_XS" },
                 ],
  summary     => "Comparing the speed of JSON decoders (2015)",
};

1;
# ABSTRACT: Comparing the speed of JSON decoders (2015)

