# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:05:03 2018 from module list in Acme::CPANLists::Import::ORM version 0.03.

package Acme::CPANModules::Import::ORM;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://www.perlmonks.org/?node_id=700283] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Alzabo" },
                   { module => "Catalyst" },
                   { module => "Class::DBI" },
                   { module => "Class::Trigger" },
                   { module => "DBI" },
                   { module => "DBIx::Class" },
                   { module => "DBIx::Class::Relationship" },
                   { module => "DBIx::Class::Schema::Loader" },
                   { module => "DateTime" },
                   { module => "Fey" },
                   { module => "Fey::ORM" },
                   { module => "Ima::DBI" },
                   { module => "Rose" },
                   { module => "Rose::DB" },
                   { module => "Rose::DB::Object" },
                   { module => "SQL::Abstract" },
                   { module => "Scalar::Defer" },
                 ],
  summary     => "Perl ORM comparison (Class::DBI vs DBIx::Class vs Rose::DB::Object) (2008)",
};

1;
# ABSTRACT: Perl ORM comparison (Class::DBI vs DBIx::Class vs Rose::DB::Object) (2008)

