# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:02:09 2018 from module list in Acme::CPANLists::Import::RomanNumbers version 0.03.

package Acme::CPANModules::Import::RomanNumbers;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://datetime.mongueurs.net/divers/nombres-romains/Roman_Numbers.html] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Acme::MetaSyntactic::roman" },
                   { module => "Acme::Roman" },
                   { module => "Convert::Number::Roman" },
                   { module => "Language::Befunge::lib::ROMA" },
                   { module => "Lingua::Romana::Perligata" },
                   { module => "Math::Roman" },
                   { module => "Roman" },
                   { module => "Roman::Unicode" },
                   { module => "Text::Roman" },
                 ],
  summary     => "Roman Numbers (2009)",
};

# ABSTRACT: Roman Numbers (2009)

