# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:05:03 2018 from module list in Acme::CPANLists::Import::SpellChecking version 0.03.

package Acme::CPANModules::Import::SpellChecking;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/kirk_kimmel/2012/08/an-overview-of-spell-checking-modules.html] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Apache::AxKit::Language::SpellCheck" },
                   { module => "Bing::Search::Source::Spell" },
                   { module => "Dist::Zilla::Plugin::PodSpellingTests" },
                   { module => "Dist::Zilla::Plugin::SpellingCommonMistakesTests" },
                   { module => "Dist::Zilla::Plugin::Test::PodSpelling" },
                   { module => "Gtk2::Spell" },
                   { module => "IPC::Open2" },
                   { module => "Lingua::AtD" },
                   { module => "Lingua::Ispell" },
                   { module => "Lingua::Jspell" },
                   { module => "Lingua::MSWordSpell" },
                   { module => "Lingua::Spelling::Alternative" },
                   { module => "Meta::Tool::Aspell" },
                   { module => "Perl::Critic::Policy::Documentation::PodSpelling" },
                   { module => "Pod::Spell" },
                   { module => "Pod::Spell::CommonMistakes" },
                   { module => "Pod::Spell::CommonMistakes::WordList" },
                   { module => "Pod::Spelling" },
                   { module => "Search::Tools::SpellCheck" },
                   { module => "Test::HTML::Spelling" },
                   { module => "Test::Pod::Spelling" },
                   { module => "Test::Pod::Spelling::CommonMistakes" },
                   { module => "Test::Spelling" },
                   { module => "Text::Aspell" },
                   { module => "Text::Hunspell" },
                   { module => "Text::Ispell" },
                   { module => "Text::SpellChecker" },
                   { module => "Text::SpellChecker::GUI" },
                   { module => "Tie::Ispell" },
                   { module => "WebService::KoreanSpeller" },
                 ],
  summary     => "An overview of spell checking modules (2012)",
};

1;
# ABSTRACT: An overview of spell checking modules (2012)

