# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:05:03 2018 from module list in Acme::CPANLists::Import::TemplateRoundup version 0.03.

package Acme::CPANModules::Import::TemplateRoundup;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://www.illusori.co.uk/projects/Template-Roundup/] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "App::podweaver" },
                   { module => "Cache::CacheFactory" },
                   { module => "Cache::FastMemoryCache" },
                   { module => "Cache::Ref::FIFO" },
                   { module => "HTML::Macro" },
                   { module => "HTML::Mason" },
                   { module => "Parse::Template" },
                   { module => "Perl::Critic" },
                   { module => "Solution" },
                   { module => "Template::Benchmark" },
                   { module => "Template::Sandbox" },
                   { module => "Text::Clevery" },
                   { module => "Text::Matrix" },
                   { module => "Text::Templet" },
                   { module => "Text::Xslate" },
                 ],
  summary     => "Perl Template Roundup (2010)",
};

1;
# ABSTRACT: Perl Template Roundup (2010)

