# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:05:03 2018 from module list in Acme::CPANLists::Import::TemplatingSystem version 0.03.

package Acme::CPANModules::Import::TemplatingSystem;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [https://perl.apache.org/docs/tutorials/tmpl/comparison/comparison.html] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Apache::ASP" },
                   { module => "Apache::DB" },
                   { module => "Apache::Filter" },
                   { module => "Apache::Include" },
                   { module => "Apache::PageKit" },
                   { module => "Apache::Registry" },
                   { module => "Apache::SSI" },
                   { module => "Apache::Session" },
                   { module => "Apache::Template" },
                   { module => "Apache::ePerl" },
                   { module => "CGI::Application" },
                   { module => "CGI::FastTemplate" },
                   { module => "Devel::DProf" },
                   { module => "HTML::Embperl" },
                   { module => "HTML::FillInForm" },
                   { module => "HTML::Mason" },
                   { module => "HTML::Template" },
                   { module => "HTML::Tree" },
                   { module => "IPC::SharedCache" },
                   { module => "Template::TAL" },
                   { module => "Text::Template" },
                   { module => "Time::HiRes" },
                   { module => "XML::LibXML" },
                   { module => "XML::XSLT" },
                 ],
  summary     => "Choosing a templating system (2014)",
};

1;
# ABSTRACT: Choosing a templating system (2014)

