# This file is automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 06:02:09 2018 from module list in Acme::CPANLists::Import::ThreadPoolForBossWorkerModel version 0.03.

package Acme::CPANModules::Import::ThreadPoolForBossWorkerModel;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/kal/2012/09/thread-pool-for-a-bossworker-model.html] (retrieved on 2016-07-19). For the full article, visit the URL.",
  entries     => [
                   { module => "Beanstalk::Client" },
                   { module => "GraphViz2::Marpa" },
                   { module => "POE::Component::JobQueue" },
                   { module => "Parallel::Workers" },
                   { module => "Thread::Apartment" },
                   { module => "Thread::Pool" },
                   { module => "Thread::Queue" },
                   { module => "Thread::Semaphore" },
                   { module => "Thread::Workers" },
                   { module => "threads::shared" },
                 ],
  summary     => "Thread pool for a boss/worker model (2012)",
};

# ABSTRACT: Thread pool for a boss/worker model (2012)

